### ISSUE TITLE
Closures where all non-optional arguments are closed

### ISSUE THREAD

**Issue by jameshume** [dhmunro/yorick#18]
Hi, 

The following is a dummy little test to demonstrate the problem. Not sure if there is a way to do this?

In the following I have a function `canCloseMe`. When the function is closed to the variable `tmp`, I cannot then call `tmp()`, it throws an error. I can call `tmp(other=something)` to get the return value correctly. Is there a way to just call `tmp()`.

I have found that I can do `tmp.function(tmp.data)` but this seems to be long winded considering what the closure syntax is for...

Thanks

```
func anyFunc(void) {
   return 99;
}

func canCloseMe(a, other=) {
   print, a * 10;
   print, other;
   return save(memb=a*10);
}


tmp = closure(canCloseMe, [1,2,3])
a = tmp( other="test")
b = tmp
c = anyFunc()

print ,"INFO A"
info, a
print, a

print ,"INFO B"
info, b
print, b

print, "INFO C"
info, c
print, c

print, "The failure should be caught"
if (!catch(-1))
{
   b2 = tmp() // ERRROR HERE
   print ,"INFO B2"
   info, b2
   error, "THIS SHOULD HAVE FAILED";
}

print, "But this works?"
tmp.function(tmp.data)
```

**Comment by dhmunro** [comment]
This has nothing to do with closures.  A misfeature of yorick syntax/semantics is that the language provides no way to invoke a function in an expression without passing it at least one argument.  The closest you can come is what you did, ``f()``, which passes ``f`` a single nil argument, exactly equivalent to ``f([])`` by yorick's semantics.  Yorick syntax also distinguishes between invoking a function and invoking a subroutine; the statement ``f;`` invokes ``f`` as a subroutine with no arguments, but it also discards any return value.  There simply is no syntax in yorick to both pass zero arguments and not ignore any return value.  This is different from both C and python, where ``f()`` passes zero arguments.  On the other hand, in C and python, you cannot simply omit an argument to pass nil to a function: ``f(a,,c)`` passes a nil second argument in yorick, but is a syntax error in both C and python.  I judged such dropouts more important than the side effect that ``f()`` passes a single nil argument when I was designing yorick.

The workaround is to provide an unused dummy parameter in your function definition.  Conventionally I have named such a parameter ``void``:

    func f(void) { return 42; }

In your case, the fact that your function is a closure means that there is no way to pass it fewer than two arguments (unless you invoke it as a subroutine and discard its return value).  Hence, you need a dummy second parameter:

    func canCloseMe(a, void, other=) {
       print, a * 10;
       print, other;
       return save(memb=a*10);
    }

This will work as you originally intended; the ``void`` parameter gets set to the single ``[]`` argument when you invoke your closure as ``tmp()``, which is exactly what the error message said.  Of course it sounds obscure until you realize that what you assumed you were doing -- invoking ``tmp`` with zero arguments -- is simply impossible in yorick.  Perhaps it would be clearer if you called your dummy parameters ``dummy`` instead of ``void``.  Unlike C, the name ``void`` has no special meaning in yorick; it's still a parameter.  Yorick does permit you to define a function of zero arguments, but the syntax is this:

    func hello_world { "Hello, world!"; }

This is useful as a sort of macro, but there is no way to invoke it except as a subroutine, so, like this function, there's no point in an explicit ``return`` statement at the end.

The important point in all of this is that your problem is with the meaning of ``tmp()``, which is pass a single ``[]``-valued argument to ``tmp``.  It has nothing to do with what kind of thing ``tmp`` is.  The ``void`` in your ``anyFunc`` example is a real argument, it's simply unused.

**Comment by jameshume** [comment]
Hi, thanks for such a quick and detailed reply. Much appreciated
